FROM ubuntu:20.10
RUN apt-get update && \
	apt-get dist-upgrade -y && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y cargo libssl-dev libgtk-3-dev && \
	rm -rf /var/lib/apt/lists/*

RUN useradd -m user
USER user
WORKDIR /home/user

RUN cargo install cargo-deb
COPY . .
RUN cargo deb
