name: Build packages
on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
jobs:
  old_build:
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt-get install -y libssl-dev libgtk-3-dev
      - run: cargo install cargo-deb cargo-rpm

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: target-dir-cache-old-release
          path: target/

      # needed on older glibc
      - run:  sed -i 's/resolv.*/resolv = "0.2.0"/' Cargo.toml

      - run: cargo deb

      - run: mv target/debian/timer-for-harvest_*_amd64.deb .
      - run: sha256sum *.deb > SHA256SUM

      - uses: actions/upload-artifact@v2
        with:
          name: old_openssl
          path: |
            timer-for-harvest_*_amd64.deb
            SHA256SUM
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install -y libssl-dev libgtk-3-dev
      - run: cargo install cargo-deb cargo-rpm

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: target-dir-cache-release
          path: target/

      - run: cargo deb
      - run: cargo rpm build

      - run: mv target/debian/timer-for-harvest_*_amd64.deb .
      - run: mv target/release/rpmbuild/RPMS/x86_64/timer-for-harvest*.rpm .
      - run: sha256sum *.deb *.rpm > SHA256SUM

      - uses: actions/upload-artifact@v2
        with:
          name: new_openssl_packages
          path: |
            timer-for-harvest_*_amd64.deb
            timer-for-harvest*.rpm
            SHA256SUM