name: Build packages
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-deb:
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt-get install -y libssl-dev libgtk-3-dev
      - run: cargo install cargo-deb cargo-rpm
      
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: target-dir-cache-release
          path: target/
          
      - run: cargo deb
      - run: cargo rpm build
      - run: find target/release/rpmbuild

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            target/debian/timer-for-harvest_*_amd64.deb
            target/release/rpmbuild/RPMs/*.rpm
