name: Tests
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libssl-dev libgtk-3-dev
      
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: target-dir-cache
          path: target/

      - run: cargo build
      - run: cargo test
  
