name: Tests
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libssl-dev libgtk-3-dev
      
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: target-dir-cache
          path: target/

      - run: cargo build
      - run: cargo test
  
  build-deb:
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt-get install -y libssl-dev libgtk-3-dev
      - run: cargo install cargo-deb
      
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: target-dir-cache-release
          path: target/
          
      - run: cargo deb

      - uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: target/debian/timer-for-harvest_*_amd64.deb
